version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: publiclab-editor
    versions:
    - 3.0.1
    - 3.0.2
  - dependency-name: jasmine
    versions:
    - 3.6.4
  - dependency-name: grunt
    versions:
    - 1.3.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
